### PR TITLE
june 2018 newsletter

### PR DESCRIPTION
**Pull request by rainleander**

### CODE REVIEW

**Comment by mscherer** [comment]
CI fail because kramdown was updated last week, and i suspect the issue is https://github.com/gettalong/kramdown/pull/513/files 

So either we do fix the version to 1.16, or we find what broke exactly. I am not confident enough in Ruby to find the right fix.

**Comment by mscherer** [comment]
So one fix is pushed in #1219 , so once it is merged, you would need to rebase your PR on top of that fix.

**Comment by rainleander** [comment]
How?

**Comment by mscherer** [comment]
I merged my fix, so it should just be a matter of fetch the latest version of the master branch, and rebase your branch on top of it, something along the line of : "git checkout master ; git pull --rebase ; git checkout june-2018-newsletter ; git rebase master ; git push" if I am not wrong (but I didn't sleep last night and still off from work, so can't be 100% sure of my instruction )

**Pull request closed without merging**
