### PR TITLE
Updated gettingstartedicehouse-w-gre.html.md

### PR DESCRIPTION
**Pull request by Akasurde**
Minor updates

### CODE REVIEW

**Comment by apevec** [comment]
Icehouse is EOL, references to this release should be removed from docs
@rbowen here we have release in the title/URL - how to change that?
@mangelajo @booxter is all of this content relevant for the latest Liberty release or some updates are needed?

**Comment by apevec** [comment]
Also ping @radez as the original wiki author.

**Comment by booxter** [comment]
I think that we lately had no issues with NetworkManager vs. neutron.

firewalld is probably not a good idea anyway though it may actually work now. You will need to have iptables and ip6tables services enabled instead.

Also the suggestion to disable SELinux is definitely not something we should make for Liberty. There may be issues somewhere, yes, but generally we should assume it should work, and report bugs.

**Comment by booxter** [comment]
Also I don't get why we suggest to touch CONFIG_SWIFT_INSTALL=y for GRE. It's completely irrelevant.

And finally, the page talks about some workshop. Those references probably need a cleanup.

**Comment by rbowen** [comment]
We'd need to rename the file, and update all links to it. I thought I'd purged all Icehouse refs.

**Pull request merged**
