### PR TITLE
CentOS dojo @ CERN blog post

### PR DESCRIPTION
**Pull request by hguemar**

### CODE REVIEW

**Comment by apevec** [comment]
@rbowen @duck-rh  this has not been published yet while newer blog post about mlist changes already  showed up at https://www.rdoproject.org/blog/ - any ideas where is it stuck?

**Comment by duck-rh** [comment]
Indeed, the post is marked as `published: false`.

**Comment by duck-rh** [comment]
@hguemar  is it an intentional WIP post?

**Comment by duck-rh** [comment]
So there's another problem you can see here: https://www.rdoproject.org/build_log.txt

For some reason the build in the CI generate the "Cloud SIG" tag as "cloudsig" while the builder has a space in it and fails.

I think anyway tags are not supposed to include spaces and using dashes instead would be more readable.

I'm going to push a fix to unblock the builder.

**Pull request merged**
