### PR TITLE
refactored style & split SASS into several files

### PR DESCRIPTION
**Pull request by garrett**

### CODE REVIEW

**Comment by garrett** [comment]
I've come back to this and it isn't building. I don't know why. So frustrating. If it fails now, it should've failed before. But it worked fine before, but not now. :cry:

**Comment by rbowen** [comment]
I'm not sure what to do with this. Should I go ahead and merge it, or is it permanently broken?

**Comment by garrett** [comment]
Rebased on master.

**Comment by garrett** [comment]
@rbowen: It's a work-in-progress for issue #75. In the issue (linked in this PR), I said to not merge it, as it's not done. 

It's a pull request for review and to have it run in the CI. I'll merge it when it's ready. 

This effort was pushed to the backburner so that I could work on launch-critical items (events, mainly).

I did a force push (something generally not recommended, unless you're a git Jedi and know _exactly_ what you're doing) to update the changes (after I rebased it to be on top of master) and re-run CI.

For whatever reason(s), it's still not working during CI build.

https://travis-ci.org/redhat-openstack/website/builds/85702453#L1236

It basically comes down to `@extend`s not working, for some mysterious reason. (They work just fine in the all-in-one `theme.sass` file and also while running the server locally, so it's really hard to figure out why this is happening.)

**Pull request closed without merging**
