### PR TITLE
Added community meeting minutes for 06-13-2018

### PR DESCRIPTION
**Pull request by mjturek**

### CODE REVIEW

**Comment by duck-rh** [comment]
@rainleander what do you expect us to do on this ticket?
All I see is a change by @mjturek which needs to be rebased and conflicts resolved. I tried to use the "resolve conflicts" function but to no avail. With just one line of change @mjturek should not have much difficulty.

**Comment by rainleander** [comment]
It looks like it should just work? I don't know why it won't let me.

**Comment by duck-rh** [comment]
@rainleander  git does not know how to merge these changes because the file has already been changed in master around the same line. I sent you some notes on how to solve a conflict. ANyway as I said @mjturek should do it on his branch and then we can merge.

**Comment by rainleander** [comment]
Hello Mike! Could you please resolve this conflict so that it can be merged? Let me know if you need any assistance.

**Comment by rainleander** [comment]
Cherry picked this update into my pull request [1239] for yesterday's meeting.

**Pull request closed without merging**
