### PR TITLE
Fixed some typos from feedback.

### PR DESCRIPTION
**Pull request by amoralej**
Maintain as unpublished until further notice.

### CODE REVIEW

**Comment by rbowen** [comment]
What's the status of this? Can we publish it yet?

**Comment by amoralej** [comment]
Not yet. We must wait until we have finished the migration to new dlrn server in ci.centos. Should be ready soon.

**Comment by hguemar** [comment]
ping status :)

**Comment by apevec** [comment]
still on hold, pending migration to new dlrn server in ci.centos

**Pull request closed without merging**
