### PR TITLE
added missing icons

### PR DESCRIPTION
**Pull request by garrett**
I think these are from the MediaWiki days (many years ago).

Nevertheless, they're referenced in CSS and causing 404s. So I've added them back.

I'm not sure if any pages actually use the styles, but here they are.

### CODE REVIEW

**Comment by garrett** [comment]
Added icons to fix a few 404s in #1074.

**Comment by mary-grace** [comment]
@duck-rh @mscherer @rbowen - could one of the three of you look at this please? I'm sure everything's ok, but just want a gut check from others who know the site far better than I :)

**Comment by rbowen** [comment]
I'm not understanding why we're adding icons that aren't actually used anywhere, but, on the other hand, it certainly doesn't appear to break anything, so I guess it looks ok to me.

**Comment by mary-grace** [comment]
if they truly aren't used anywhere, can we change the CSS instead?

**Comment by mscherer** [comment]
I would be of @mary-grace opinion of cleaning if I was sure they were unused.
But I do not know enough css to tell what is going on. It seems they are used with some url matching, so maybe they are used somewhere.

**Comment by mary-grace** [comment]
@garrett thoughts on whether it's better to add the styles/icons as you've done, or simply remove the links in the CSS?

**Comment by pmkovar** [comment]
My take on this is that I'd rather live with a few 404's than adding unnecessary clutter but YMMV.

**Pull request merged**
