### PR TITLE
Dec17 newsletter

### PR DESCRIPTION
**Pull request by mary-grace**
added Dec17 newsletter & fixed some of the generic links (release schedule, mailing lists, etc.) from previous newsletters. also updated the newsletter template.

### CODE REVIEW

**Comment by mary-grace** [comment]
@rbowen - If you have a chance/feel the need to look this over before tomorrow morning, feel free to push it live after you've perused. Otherwise I'll push it through tomorrow AM PST.

**Comment by mary-grace** [comment]
@mscherer @duck-rh - looks like this is having similar issues as the rh-events repo. The Travis build is failing because it can't find the correct gems. I had to update the `eventmachine` gem on my side before Middleman would run for my local version, so I'm guessing there's something missing/outdated on the back end.

**Comment by mary-grace** [comment]
It actually looks like the issue might be the SSL cert on https://rails-assets.org/. I'm guessing there's not much we can do about this. Any reason why I shouldn't push it through in the morning?

**Comment by rbowen** [comment]
I'm very nervous about pushing a pr with failures. This has bitten us before. Any ideas @duck-rh?

**Comment by rbowen** [comment]
Rerunning the tests, and one of the two has passed fine this time. Here's hoping ...

**Pull request merged**
