### PR TITLE
improved docs

### PR DESCRIPTION
**Pull request by kardithSingh**

### CODE REVIEW

**Comment by kardithSingh** [comment]
@gbraad @garrett @jeckersb @jpichon merge

**Comment by gbraad** [comment]
please no

**Review by gbraad — CHANGES_REQUESTED** [review]
These additions are not in line with the project.

**Comment by supersaiyanmode** [comment]
I came here from Twitter (shitoberfest). I have seen around 30-50 PRs across several projects now. It's extremely disappointing what some of these folks are doing for a T-Shirt.

That being said, please don't generalize Indians on the basis of what's happening here. Cheers!

**Comment by duck-rh** [comment]
@supersaiyanmode I'm looking at each and every PR I'm closing, and I don't care about the account name or where people come from.

**Comment by supersaiyanmode** [comment]
Thank you for not looking at names or country of origin. And now that I think about it -- sorry for spamming here without anything substantial to add.

**Pull request closed without merging**
