### PR TITLE
List past, upcoming test days

### PR DESCRIPTION
**Pull request by rbowen**

### CODE REVIEW

**Comment by garrett** [comment]
Events updating should not go into pull requests. Having multiple probably made this fail.

I sync'd with master locally, verified rh-events is valid (it should be if people ensure checks pass during a PR and/or locally via the validate script — but wanted to make sure), updated events, pushed the updated events, then cherry-picked the commit that you wanted in this PR into a new branch, and finally sent your page change commit as a separate PR (as I couldn't update this one as it is your own branch).

**Comment by garrett** [comment]
**TL;DR**: Made my own PR based on your commit, ensured it worked, and merged it instead. :wink:

**Comment by rbowen** [comment]
On 11/20/2015 05:30 AM, Garrett LeSage wrote:
> Events updating should not go into pull requests. Having multiple
> probably made this fail.
> 
> I sync'd with master locally, verified rh-events is valid (it should be
> if people ensure checks pass during a PR and/or locally via the validate
> script — but wanted to make sure), updated events, pushed the updated
> events, then cherry-picked the commit that you wanted in this PR into a
> new branch, and finally sent your page change commit as a separate PR
> (as I couldn't update this one as it is your own branch).

I don't know how to do any of those things. It would probably be helpful
to know. All I did in any of these cases was to `git pull upstream
master` before I did my commits, to ensure that I was in sync. I don't
know what those other events updatings were - they just came along for
the ride.

For all that people say Git is wonderful, it is still a basket of deep
mysteries to me.


-- 
Rich Bowen - rbowen@redhat.com
OpenStack Community Liaison
http://rdoproject.org/

**Comment by garrett** [comment]
The local script automatically syncs up the events and makes a commit as the person who ran it. Whenever events change, those commits show up.

If you make sure master is up-to-date remotely, then the commits would show in both branches, and therefore will not show up in the pull request. (That is, unless the changes are actually different commits for whatever reason in both branches.)

--

You can also rebase your feature branch on top of master before you push it to the server. Or, if it's only your own branch, made for the purpose of a pull request only, then you can rebase and even force push that branch. 

However, I don't suggest force pushing, unless you are *certain* you know what you're doing, as force pushing to a shared remote branch — especially `master` (like, on accident) — is a _very, **very**_ bad thing to do. If you want to make sure the shotgun of a force push isn't pointed at your feet (or anyone else's), then you can do a dry-run for the git push, with either `--dry-run` or `-n` (shorthand; you can think of it as `-n`ope). As a command it'd look like `git push -f -n` or `git push --force --dry-run` (if you really like to type a lot and/or be explicit in your commands). Of course, you can combine that with other git push options too. Dry runs help to you make sure you know what you're doing before you actually do it. :wink:

In case you're wondering why force pushing remotely share branches is a bad idea, it's because of the possible side effects. Basically, you get all versions of every divergent commit in one branch. It's like as if all the events of all three 1985 timelines in _Back to the Future_ and _Back to the Future 2_ were happening at the same time. George McFly would be a wimp, confident, and dead all at the same time. Biff would be a bully, subservent, and rule the land as a rich jerk all at the same time. Jennifer would be played by two actresses at the same time and mostly sleeping (so not much would change from her point of view). In other words, history would mostly be a jumbled mess. Don't cross the [time]streams.

Of course, if only one timeline of history exists, everything is peachy-keen. This is usually the scenario where you're using your own branch as a backup that other people never pull from, or as a branch a pull request is based on. Updating a branch on a pull request changes what would be merged in, so people often do push additional changes or sometimes even rebase the changes (which requires a force push to make it go to the same pull request) to make a cleaner merge before merging.

But because of the danger of people mixing in commits from multiple versions of timelines, force-push is really heavily discouraged, even if it is sometimes useful.

It's easy to push a local branch to the wrong remote. It's a little less easy with git's newish defaults (as of a year or few ago), but it's still pretty easy. That's why I suggest always doing a dry run before force pushing. Anyone can make a mistake (even if you really know what you're doing ordinarily), and it helps to see what's explicitly going to happen before.

**Comment by garrett** [comment]
The problem with git is that it gives you the tools to alter history — and any fan of Back to the Future, Star Trek, Doctor Who, The Time Machine, Bill & Ted's Excellent Adventure, 12 Monkeys, Quantum Leap, or the Terminator series can tell you that things get wibbly-wobbly when you jump around and mix timelines. Since we are all technically time travelers (traveling to the future at one minute per minute), some time travel is not so difficult, thankfully. :wink: 

git is like science fiction. The basics are basically understandable to all; some of the advanced stuff requires grokking string theory, relativity, and quantum physics. Thankfully, there's some useful stuff at all levels too.

**Pull request closed without merging**
